version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: skinify-mysql
    restart: always
    environment:
      MYSQL_DATABASE: skinify
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-app:
    build: .
    container_name: skinify-auth-service
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_URL=jdbc:mysql://mysqldb:3306/skinify?useSSL=false&allowPublicKeyRetrieval=true

volumes:
  mysql-data:
